version: "3.7"

services:
  mongo0:
    image: mongo:4.2
    hostname: mongo0
    restart: always
    command: /usr/bin/mongod --bind_ip_all --replSet rs0 --port 27017
    ports:
      - 27017:27017
    networks:
      - local

  mongo1:
    image: mongo:4.2
    hostname: mongo1
    restart: always
    command: /usr/bin/mongod --bind_ip_all --replSet rs0 --port 27018
    ports:
      - 27018:27018
    networks:
      - local

  mongo2:
    image: mongo:4.2
    hostname: mongo2
    restart: always
    command: /usr/bin/mongod --bind_ip_all --replSet rs0 --port 27019
    ports:
      - 27019:27019
    networks:
      - local

  document:
    build: .
    image: document:0.0.1-SNAPSHOT
    hostname: document
    ports:
      - 8080:8080
    init: true
    depends_on:
      - mongo0
      - mongo1
      - mongo2
    networks:
      - local

networks:
  local:
